language: python
python:
  - "3.3"
  - "3.4"
install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"
script:
  - "coverage run --source=canalplus setup.py test"
after_success:
  - "coveralls"
